### ISSUE TITLE
Include "Recently starred repositories"

### ISSUE THREAD

**Issue by felixschndr** [felixschndr/felixschndr#3]
https://github.com/lowlighter/metrics

```
  # ====================================================================================
  # 🌟 Recently starred repositories
  
  # Enable or disable plugin
  plugin_stars:
    description: Display recently starred repositories
    default: no
  
  # Number of stars to display
  plugin_stars_limit:
    description: Maximum number of stars to display
    default: 4
```
